### ISSUE TITLE
Instance STRATHOLME

### ISSUE THREAD

**Issue by yettounette** [EpsiloneDev/Exorsium-Server#2]
# **Steps to reproduce the problem**:

Ils n'attaquent pas, tu t'approche d'eux ya pas de réaction, ils ne peuvent ni attaquer ni se faire attaquer, sa marque comme Cible Incorrecte.
Cannon au last boss bugent, on peut obtenir les Cannonball mais on peut pas utiliser les cannons.

**Include proofs for this behaviour**

Skeletal Guardian                :      10390
Skeletal Berserker                :      10391
Skeletal Servant                   :      8477
Ravaged Cadaver                 :      10381
Mangled Cadaver                 :      10382
Plague Ghoul                        :      10405
Fleshflayer Ghoul                  :      10407
Patchwork Horror                  :      10414
Magistrate Barthilas               :      10435
Wailing Banshee                     :      10464
Crypt Beast                              :      10413
Thuzadin Necromancer           :      10400
Thuzadin Shadowcaster           :      10398
Rockwing Gargoyle                  :      10408
Baroness Anastari                     :      10436
Maleki the Pallid                        :      10438
Venom Belcher                           :      10417
Nerub'Enkan                               :      10437
Bile Spewer                                 :      10416
Summoned Zombie                    :      10698
Ramstein The Gorger                  :      10439
Mindless Undead                        :      11030
Black Guard Sentry                      :      10394
Baron Rivendare                          :      10440

Cannon Bug 
CannonBall                :    176215
Scarlet Cannon :          :    176216
scarlet cannon 2 :        :    176217

**Include Screenshots from the issue if necessary**
![wowscrnshot_052518_180823](https://user-images.githubusercontent.com/39626938/40557332-aab1f56c-6047-11e8-9f70-30d4a438ad72.jpg)
![wowscrnshot_052518_181235](https://user-images.githubusercontent.com/39626938/40557333-aad4a422-6047-11e8-95d7-8c9c81fb4ee8.jpg)
![wowscrnshot_052518_181248](https://user-images.githubusercontent.com/39626938/40557334-aaf77aba-6047-11e8-8d98-c71f4baa715a.jpg)
![wowscrnshot_052518_184813](https://user-images.githubusercontent.com/39626938/40558735-420126b4-604c-11e8-9831-3cc5e63cf9bf.jpg)

**Comment by EpsiloneDev** [comment]
Je prend en charge se ticket

**Comment by EpsiloneDev** [comment]
Fixed
