### ISSUE TITLE
Naxxramas

### ISSUE THREAD

**Issue by yettounette** [EpsiloneDev/Exorsium-Server#5]
**Informations**:

Les créatures n'attaquent pas, ils n'ont aucune réaction ainsi que les boss !
Kelthuzad ne passe pas sa phase 2 dés la phase 1 il disparait.

**Steps to reproduce the problem**:

Les boss doivent être attaquable pour vérifié leurs phases.

**Include proofs for this behaviour**

- [x] - Grand Widow Faerlina           :     15953
- [x] - Maexxna                                 :     15952
- [x] - Death Knight Cavalier            :     16163
- [x] - Dark touched warrior             :     16156
- [x] - Death Knight                           :     16146
- [x] - Death knight Captain              :     16145
- [x] - Lady Blaumeux                       :     16065
- [x] - Thane Korth'azz             :     16064
- [x] - Baron Vaillefendre          :     30549
- [x] - Sir Zeliek                  :     16063
- [x] - Infectious Ghoul            :     16244
- [x] - Plagued Ghoul               :     16447
- [x] - Stoneskin Gargoyle          :     16168
- [x] - Loatheb                     :     16011
- [x] - Anub'Rekhan                 :     15931
- [x] - Stitched Colossus           :     30070
- [x] - Stitched Colosse            :     30071
- [x] - Marauding Geist             :     30083
- [x] - Noth the Plaguebringer      :     15954
- [x] - Heigan the Unclean          :     15936
- [x] - Necro Knight                :     16165
- [x] - Shade of Naxxramas          :     16164
- [x] - Skeletal Smith              :     16193
- [x] - Bony Construct              :     16167
- [x] - Risen Squire                :     16154
- [x] - Deathcharger Steed          :     16067
- [x] - Death Knight Understudy     :     16803
- [x] - Instructor Razuvious        :     16061
- [x] - Unholy Axe                  :     16194
- [x] - Unholy Staff                :     16215
- [x] - Unholy Sword                :     16216
- [x] - Necro Knight                :     16165
- [x] - Gothik the Harvester        :     16279
- [x] - Unrelenting Trainee         :     16124
- [x] - Unrelenting Death Knight    :     16125
- [x] - Unrelenting Rider           :     16126
- [x] - Feugen                      :     15930
- [x] - Stalagg                     :     15929
- [x] - Thaddius                    :     15928
- [x] - Gluth                       :     15932
- [x] - Stitched Giant              :     16025
- [x] - Grobbulus                   :     16035
- [x] - Patchwerk                   :     16174
- [x] - Sludge Belcher              :     16029
- [x] - Living Monstrosity          :     16021
- [x] - Surgical Assistant          :     16022
- [x] - Mad Scientist               :     16063
- [x] - Bile Retcher                :     16018
- [x] - Patchwork Golem             :     16017
- [x] - Embalming Slime             :     16024
- [x] - Sapphiron                   :     15989
- [x] - Kel'Thuzad                  :     15990

**Include Screenshots from the issue if necessary**
![wowscrnshot_052518_223352](https://user-images.githubusercontent.com/39626938/40567155-1c17a020-606c-11e8-88f7-2edd708690c4.jpg)
![wowscrnshot_052518_223407](https://user-images.githubusercontent.com/39626938/40567156-1c3ca758-606c-11e8-8998-18bca342675d.jpg)

**Comment by EpsiloneDev** [comment]
Creatures Wrong Faction .
Fixed !
