### ISSUE TITLE
Icecrown Citadel

### ISSUE THREAD

**Issue by yettounette** [EpsiloneDev/Exorsium-Server#6]
Informations :

Mobs et 3/4 des boss non attaquable, 
Pour le reste des boss ils sont bien script
Blood-Queen Lana'Thel       :     37955   ( Elle ne passe pas ses phases ( Mannequin d'entrainement ) )
Les haut faits sont bien dans leurs places, 

Steps to reproduce the problem:

Corriger le bug, après je vais vérifié les phases de chaque boss non vérifié.

Include proofs for this behaviour

- [ ] 
- [x] The Damned                         :     37011
- [x] Servant Of the throne           :     36724
- [x] Ancient Skeletal Soldier        :     37012
- [x] Deathbound Ward                 :     37007
- [x] Lord Marrowgar                    :     36612
- [x] Lady Deathwhisper                :     36855
- [x] Frenzied Abomination            :     37546
- [x] Spire Gargoyle                        :     37544
- [x] Spire Minion                           :     37545
- [x] The Skybreaker                         :     37540
- [ ] Deathbringer Saurfang              :     37813
- [x] Blighted Abomination              :     37022
- [x] Plague Scientist                     :     37023
- [x] Vengeful Fleshreaper               :     37038
- [x] Pustulating Horror          :     10404
- [x] Stinky                      :     37025
- [x] Precious                    :     37217
- [x] Decaying Colossus           :     36880
- [x] Festergut                   :     36626
- [ ] Blood-Queen Lana'Thel       :     37955   ( Elle ne passe pas ses phases ( Mannequin d'entrainement ) )
- [x] Ymirjar Huntress            :     37134
- [x] Ymirjar Warlord             :     37133
- [x] Ymirjar Battle-Maiden       :     37132
- [x] Ymirjar Deathbringer        :     38125
- [x] Ymirjar Frostbinder         :     37127
- [x] Ymirjar Huntress            :     37134
- [x] Sister Svalna               :     37126
- [x] FrostWarden Handler         :     37531
- [x] Rimefang                    :     37533
- [x] Spinestalker                :     37534
- [x] Sindragosa                  :     36853
- [ ] The LICH KING               :     36597
- [ ] 

Include Screenshots from the issue if necessary

![wowscrnshot_052518_225633](https://user-images.githubusercontent.com/39626938/40569566-9c263110-607a-11e8-9956-2dee4a501e56.jpg)
![wowscrnshot_052618_001338](https://user-images.githubusercontent.com/39626938/40569567-9c488ca6-607a-11e8-96d6-1415b97185b1.jpg)
![wowscrnshot_052618_002026](https://user-images.githubusercontent.com/39626938/40569568-9c701636-607a-11e8-9749-5414b208a114.jpg)

**Comment by EpsiloneDev** [comment]
Faction fixed , [Saurfang,LK,Blood Queen] Need fix c++
create a new Issue with more information for saurfang , the lich king and Blood-Queen Lana'Thel
